### ISSUE TITLE
영어 한글발음 고유명사 변환

### ISSUE THREAD

**Issue by Moon-sung-woo** [YiHoze/texwrapper#2]
안녕하세요.
좋은 코드 올려주셔서 감사합니다.
hello, name과 같은 단어들에 대해서는 헬로, 네임 으로 한글발음 변환이 잘 되는것을 확인했습니다.

하지만 'sungwoo'와 같은 고유명사에 대해서는 '성우'로 발음 변환이 안되던데
혹시 변환할 수 있는 방법이 있을까요?

감사합니다.

**Comment by YiHoze** [comment]
제 블로그(https://hoze.tistory.com/2043)에서 밝힌 바와 같이, CMU라는 사전이 사용되는데, 사전에 등재되지 않은 단어에 대해서는 발음 정보를 알 수 없으므로 처리할 수 없습니다. 그와 같은 예외적인 경우들을 위해 사전 변수가 하나 만들어져 있습니다.

        self.errata = {
            'cloche':'klouʃ',
            'our':'auər',
            'penguin':'peŋgwin',
            'target':'ˈtɑrgɪt',
            'to':'tu',
            'when':'wen'
        }

여기에 sungwoo와 그것의 발음 기호를 추가하시면 되겠습니다. 데이터가 지나치게 많으면 이 변수를 파일로 만들어야겠지요.
hanroman.py는 신뢰할 만한 음역기가 아닙니다. 어떤 음운 변화들이 어떤 순서로 일어나는지, 또 예외가 무엇인지, 제가 충분히 이해하고 있지 못하기 때문입니다. 혹시 이 분야에 전문가시라면 제 코드를 참고하여 더 나은 스크립트를 만들어주시기 바랍니다.
